server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
